### ISSUE TITLE
 Node version not specified in package.json

### ISSUE THREAD

**Issue by Ponraj-Mavjay** [opentok/opentok-archive-transcription-demo#2]
Hi, 
I followed all the step and got my secret keys and buckets. I tried deploying the demo application in heroku, it asked for all credentials and once i entered everything i got this error.

-----> Building dependencies
       Installing node modules (package.json + package-lock)
       
       > grpc@1.7.3 install /tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc
       > node-pre-gyp install --fallback-to-build --library=static_library
       
       node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
       node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.13.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
       node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
       node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.13.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
       make: Entering directory '/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/build'
       make: Entering directory '/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/build'
         CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
         CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
       rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
       grpc.target.mk:405: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o' failed
       make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
       make: Leaving directory '/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
       gyp ERR! System Linux 4.4.0-1031-aws
       gyp ERR! command "/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/bin/node" "/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
       gyp ERR! cwd /tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc
       gyp ERR! node -v v10.13.0
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok 
         CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
       node-pre-gyp ERR! build error 
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/bin/node /tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
       node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
       node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
       node-pre-gyp ERR! System Linux 4.4.0-1031-aws
       node-pre-gyp ERR! command "/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/bin/node" "/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
       node-pre-gyp ERR! cwd /tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc
       node-pre-gyp ERR! node -v v10.13.0
       node-pre-gyp ERR! node-pre-gyp -v v0.6.39
       node-pre-gyp ERR! not ok 
       Failed to execute '/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/bin/node /tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
         CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
         CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
       In file included from ../deps/grpc/src/core/lib/channel/channel_stack_builder.h:24:0,
                        from ../deps/grpc/src/core/lib/channel/channel_stack_builder.c:19:
       ../deps/grpc/src/core/lib/channel/channel_args.h:23:10: fatal error: grpc/grpc.h: No such file or directory
        #include <grpc/grpc.h>
                 ^~~~~~~~~~~~~
       compilation terminated.
       grpc.target.mk:405: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o' failed
       make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o] Error 1
       make: Leaving directory '/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
       gyp ERR! System Linux 4.4.0-1031-aws
       gyp ERR! command "/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/bin/node" "/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
       gyp ERR! cwd /tmp/build_3f364b46aa3e58f83e49f75f5f1fdab2/node_modules/grpc
       gyp ERR! node -v v10.13.0
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok 
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the grpc@1.7.3 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.aZ8xt/_logs/2018-11-26T09_40_16_293Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

I don't how to proceed with this. Can you help me with this

**Comment by kpremsai** [comment]
Hii,
yes  i am also getting same error when i was deploying in heroku
Can you please anybody
       Thank you
